### PR TITLE
-Removed schema inference section for CDT.

### PR DESCRIPTION
**Pull request by rahul-aerospike**
-Made few key sections bold.
-Moved schema introduction section to the top.

### CODE REVIEW

**Comment by rahul-aerospike** [comment]
@kmatty26

**Review by kirmatty26 — COMMENTED** [review]
As discussed, could you please add the note: “We recommend that you provide schema for queries that involve complex data types such as lists, maps, and mixed types. Using schema inference for CDT may cause unexpected issues." Make it bold. 

Let's not go into the issues since we haven't spent a lot of time on it and we do not think its worthwhile to do it unless it become a blocker for a certain use case.

**Comment by rahul-aerospike** [comment]
resolved merge conflicts.

**Review by arrowplum — COMMENTED** [review]
Can you reset this and strip the output before fully merging it in?

Also is there a way to show the expected errors in a more controlled way? Like catching the exception and printing the relevant parts? (so it doesn't look like there was an actual error with the execution)

**Pull request merged**
