### PR TITLE
TUT-21 Merge the two current notebook github repos into one.

### PR DESCRIPTION
**Pull request by pvinh-spike**
Hi Neel,
I did some tests and it seem ok.

Please verify and let me know if anything missing.

Thanks,

Phuc Vinh

### CODE REVIEW

**Comment by neelp-git** [comment]
Hi Phuc, I would go with the results of these tests:

1. Binder works in the merged branch. [Neel]
2.  The built Docker container works. [Phuc/Lucien]
3. Spark notebook continues to work with the build instructions for Linux and MacOS. [Kiran/Rahul]

Can you please make sure the testing is completed in the branch, after which we can merge. Thanks.

**Comment by pvinh-spike** [comment]
Hi Neel,

2. The built Docker container works.

I did build & test (using Lucien instruction) and all passed, but it’s better to have Lucien verify.

Thanks,

Phuc Vinh

**Comment by neelp-git** [comment]
My binder launch from the branch fails:
...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Removing intermediate container 537d9bbc6ce4
 ---> dadc62cf2f01
Step 12/20 : COPY aerospike.template.conf /etc/aerospike/aerospike.template.conf
 ---> 11827bbcbaeb
Step 13/20 : COPY entrypoint.sh /entrypoint.sh
 ---> fd4ff3cf94aa
Step 14/20 : COPY spark /home/$NB_USER/spark
COPY failed: stat /ssd/docker/tmp/docker-builder045304997/spark: no such file or directory

**Review by neelp-git — COMMENTED** [review]
The changes in the Dockerfile.md and main README.md are instructions which need to be updated with the new repo name - that's good. But the binder launch failure on mybinder.org  is not addressed with these changes. Also, notebooks/README.md is a generated file, generated by running update_readme.sh script. The binder launch URLs in it are populated by the script, and need not be directly updated.

**Comment by pvinh-spike** [comment]
Just talk to Rahul and he confirmed that it's ok to merge.

**Pull request merged**
