### PR TITLE
Tweet a spike example java project

### PR DESCRIPTION
**Pull request by arrowplum**
bitmoji

### CODE REVIEW

**Comment by arrowplum** [comment]
I can't seem to request @volmarl

**Comment by mtendjou** [comment]
Thanks @arrowplum . All merged. @volmarl ball on your side I guess.

**Comment by mtendjou** [comment]
@arrowplum you can only request from folks who have write access I guess.

**Comment by mtendjou** [comment]
Which we should give to @volmarl .

**Pull request merged**
