### PR TITLE
Changes related to Spark Connector upgrade to 3.4.0

### PR DESCRIPTION
**Pull request by neelp-git**
Ignore the output cell diffs - all config changes are in the top few code cells.

### CODE REVIEW

**Comment by neelp-git** [comment]
To be merged together with the Dockerfile PR related to Spark Connector 3.4.0 upgrade. With just one merged, Spark notebooks will break.

**Review by artanderson — APPROVED** [review]
lgtm

**Review by pvinh-spike — APPROVED** [review]
LGTM

**Comment by neelp-git** [comment]
Thanks, Arthur and Phuc.

**Pull request merged**
