### PR TITLE
New Spark tutorial demonstrating simple load and store

### PR DESCRIPTION
**Pull request by neelp-git**

### CODE REVIEW

**Comment by neelp-git** [comment]
@artanderson and @rahul-aerospike, please review and approve asap - needed for the event on 8/23. Thanks.

**Comment by rahul-aerospike** [comment]
Looks good except some minor nitpick.

> This method returns data as well as metadata fields such as __key, __digest, __expiry, __generation, and __ttl
to
When schema is not specified, the connector fetches metadata columns `__key`, `__digest`, `__expiry`, `__generation`, and `__ttl` as well.

> The schema can be explicitly specified, and only these fields will be returned. Note the schema used here was constructed earlier with id, name, age, and salary fields.
to

The schema can be explicitly specified, and only specified fields will be retrieved. Note the schema used here was constructed earlier with `id`, `name`, `age`, and `salary` fields.

**Review by rahul-aerospike — APPROVED** [review]
LGTM

**Review by artanderson — APPROVED** [review]
LGTM

**Comment by neelp-git** [comment]
Thanks, @rahul-aerospike and @artanderson . I have incorporated the suggested change.

**Pull request merged**
